{
    'name': "Cine Gestión",
    'version': '1.0',
    'summary': "Gestión de Sesiones y Salas de Cine",
    'author': "Your Name",
    'category': 'Uncategorized',
    'depends': [
        'base',
    ],
    'data': [
        'security/ir.model.access.csv',
        'views/module_view.xml',
        'data/salas.xml',
        'data/generos.xml',
        'data/anuncios.xml',
        'data/cine_gestion.asiento.csv',
        #'views/anuncios_views.xml',
        #'views/descuentos_views.xml',
        #'views/eventos_views.xml',
        #'views/generos_views.xml',
        #'views/kdm_views.xml',
        #'views/salas_views.xml',
        #'views/sesiones_views.xml',
        #'views/tarifas_views.xml',
    ],
    'installable': True,
    'application': True,
}